package data;

// THIS IS AUTOGENERATED

class R {

  public static class Data {

    public static class General {
      public static final String list_of_countries_cities_and_capital =
          "data/general/list_of_countries_cities_and_capital.json";
    }

    public static class Germany {
      public static final String list_of_cities = "data/germany/list_of_cities.csv";
      public static final String list_of_names_female = "data/germany/list_of_names_female.csv";
      public static final String list_of_names_male = "data/germany/list_of_names_male.csv";
      public static final String list_of_street_names = "data/germany/list_of_street_names.csv";
      public static final String list_of_surnames = "data/germany/list_of_surnames.csv";
      public static final String list_of_words = "data/germany/list_of_words.csv";
    }

    public static class English {
      public static final String list_of_cities = "data/english/list_of_cities.csv";
      public static final String list_of_names_female = "data/english/list_of_names_female.csv";
      public static final String list_of_names_male = "data/english/list_of_names_male.csv";
      public static final String list_of_street_names = "data/english/list_of_street_names.csv";
      public static final String list_of_surnames = "data/english/list_of_surnames.csv";
      public static final String list_of_words = "data/english/list_of_words.csv";
    }

    public static class France {
      public static final String list_of_cities = "data/france/list_of_cities.csv";
      public static final String list_of_names_female = "data/france/list_of_names_female.csv";
      public static final String list_of_names_male = "data/france/list_of_names_male.csv";
      public static final String list_of_street_names = "data/france/list_of_street_names.csv";
      public static final String list_of_surnames = "data/france/list_of_surnames.csv";
      public static final String list_of_words = "data/france/list_of_words.csv";
    }

    public static class Romania {
      public static final String list_of_cities = "data/romania/list_of_cities.csv";
      public static final String list_of_names_female = "data/romania/list_of_names_female.csv";
      public static final String list_of_names_male = "data/romania/list_of_names_male.csv";
      public static final String list_of_street_names = "data/romania/list_of_street_names.csv";
      public static final String list_of_surnames = "data/romania/list_of_surnames.csv";
      public static final String list_of_words = "data/romania/list_of_words.csv";
    }

    public static class Serbia {
      public static final String list_of_cities = "data/serbia/list_of_cities.csv";
      public static final String list_of_names_female = "data/serbia/list_of_names_female.csv";
      public static final String list_of_names_male = "data/serbia/list_of_names_male.csv";
      public static final String list_of_street_names = "data/serbia/list_of_street_names.csv";
      public static final String list_of_surnames = "data/serbia/list_of_surnames.csv";
      public static final String list_of_words = "data/serbia/list_of_words.csv";
    }
  }
}
